import Vue from 'vue'
import {Link,Message,Avatar, Button,Form,FormItem,Upload ,
    Input,Row ,Col,Radio,RadioGroup,Switch,Checkbox,DatePicker,
    CheckboxButton,CheckboxGroup,Menu,Table,TableColumn,Main,Badge,
    DropdownMenu,DropdownItem,Dropdown,Header,Container,MenuItemGroup,Aside,Image,Card,
    PageHeader,Divider,Step,Steps,InputNumber,Descriptions,DescriptionsItem,
    Empty,Select,Option,Dialog,Carousel,CarouselItem,Notification,Tag,TabPane,Tabs,Loading,
    MenuItem,Submenu,Autocomplete} from 'element-ui'
Vue.use(Button)
Vue.use(Autocomplete)
Vue.use(Badge)
Vue.use(Select)
Vue.use(DatePicker)
Vue.use(Loading)
Vue.use(TabPane)
Vue.use(Tabs)
Vue.use(Tag)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Dialog)
Vue.use(Option)
Vue.use(DropdownMenu)
Vue.use(Empty)
Vue.use(Descriptions)
Vue.use(DescriptionsItem)
Vue.use(InputNumber)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Divider)
Vue.use(PageHeader)
Vue.use(Card)
Vue.use(Image)
Vue.use(Aside)
Vue.use(DropdownItem)
Vue.use(MenuItemGroup)
Vue.use(Header)
Vue.use(Container)
Vue.use(Dropdown)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Main)
Vue.use(Input)
Vue.use(Row)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Col)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Switch)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(CheckboxButton)
Vue.use(Upload)
Vue.use(Avatar)
Vue.use(Link)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.prototype.$message = Message
Vue.prototype.$notify = Notification
